# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.htfuandrew.com
title: HTFUAndrew
description: > # "Write an awesome description for your new site here.
  Health Coverage for the American Public
copyright: ''
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

